name: CI

on:
  pull_request:
    paths:
      - '.github/workflows/ci.yml'
      - '**/*.swift'
  push:
    branches:
      - master
  schedule:
    - cron: '3 3 * * 3'

jobs:
  test:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - name: Test
        run: swift test
